export const CATEGORIES = [
  { name: 'Tecnología' },
  { name: 'Hogar' },
  { name: 'Muebles' },
  { name: 'Electrodomésticos' },
  { name: 'Alimentos' },
  { name: 'Herramientas' },
  { name: 'Ropa' },
  { name: 'Documentos' },
  { name: 'Farmacéutico' },
  { name: 'Belleza' },
  { name: 'Deportes' },
  { name: 'Accesorios' },
  { name: 'Construcción' },
  { name: 'Químicos' },
  { name: 'Juguetería' },
  { name: 'Automotriz' },
  { name: 'Mascotas' },
  { name: 'Librería' },
  { name: 'Electrónica' },
  { name: 'Otros' },
];
